admin_pages/urls.py
from django.urls import path

from . import views

app_name = "admin_pages"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "team_composition/",
        views.TeamCompositionView.as_view(),
        name="team_composition",
    ),
    path("metrics/", views.MetricsView.as_view(), name="metrics"),
    path("meals/", views.MealsView.as_view(), name="meals"),
]

jeulee/urls.py
from django.contrib import admin
from django.urls import include, path
from registration import urls as registration_urls
from mainsite import urls as mainsite_urls
from admin_pages import urls as admin_pages_urls
from markdownx import urls as markdownx

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin_pages/", include(admin_pages_urls)),
    path("markdownx/", include(markdownx)),
    path("registration/", include(registration_urls)),
    path("", include(mainsite_urls)),
]

mainsite/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap

from .views import MarkdownTemplateView, RobotsView, MarkdownPagesSitemap

app_name = "mainsite"

sitemaps = {"md_pages": MarkdownPagesSitemap}

urlpatterns = [
    path("", MarkdownTemplateView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", MarkdownTemplateView.as_view(), name="md_page"),
    path("robots.txt", RobotsView.as_view(), name="robots"),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="sitemap"),
]

registration/urls.py
from django.urls import path, include

from . import views

app_name = "registration"

urlpatterns_user = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset_done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<str:uidb64>/<str:token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns = [
    path("", views.RegistrationView.as_view(), name="registration"),
    path("team/", views.TeamView.as_view(), name="team"),
    path("auth/", include(urlpatterns_user)),
    path("register_start/", views.RegisterStartView.as_view(), name="register_start"),
    path(
        "register_join_team_needs_link/",
        views.RegisterWithTeamNeedsLinkView.as_view(),
        name="register_join_team_needs_link",
    ),
    path(
        "join_team/<slug:invite_token>/", views.JoinTeamView.as_view(), name="join_team"
    ),
    path("register_infos/", views.RegisterInfosView.as_view(), name="register_infos"),
    path(
        "email_confirmation_needed/",
        views.EmailConfirmationNeededView.as_view(),
        name="email_confirmation_needed",
    ),
    path(
        "confirm_email/<uidb64>/<token>/",
        views.ConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path(
        "register_meals/", views.MealInfosSelectionView.as_view(), name="register_meals"
    ),
    path(
        "update_personal_infos/",
        views.UpdatePersonalInfosView.as_view(),
        name="update_personal_infos",
    ),
    path(
        "change_password/", views.PasswordChangeView.as_view(), name="password_change"
    ),
]

mainsite/models.py
from django.db import models
from django.urls import reverse
from markdownx.models import MarkdownxField


class MarkdownPage(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(blank=True, unique=True)
    content = MarkdownxField()
    lastmod = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "page Markdown"
        verbose_name_plural = "pages Markdown"
        ordering = ["slug"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        if self.slug:
            return reverse('mainsite:md_page', args=[self.slug])
        else:
            return reverse('mainsite:home')

mainsite/views.py
from django.views.generic import DetailView, TemplateView
from django.contrib.sitemaps import Sitemap
from django.utils.safestring import mark_safe
from shared.markdown import markdownify
from .models import MarkdownPage
from site_wide_settings.models import SiteWideSettings


class MarkdownTemplateView(DetailView):
    model = MarkdownPage
    template_name = "mainsite/base_markdown.html"

    def get_markdown_body(self):
        return mark_safe(
            markdownify(self.object.content, context=self.get_markdown_context_data())
        )

    def get_markdown_context_data(self, **kwargs):
        context = kwargs
        context["site_config"] = SiteWideSettings.get_solo()
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["markdown_body"] = self.get_markdown_body()
        return context


class RobotsView(TemplateView):
    template_name = "robots.txt"
    content_type = "text/plain"


class MarkdownPagesSitemap(Sitemap):
    def items(self):
        return MarkdownPage.objects.all()

    def lastmod(self, obj):
        return obj.lastmod

    def priority(self, obj):
        # Priorize home page over the rest in search results
        if not obj.slug:
            return 0.8
        else:
            return None # defaults to 0.5 when unset

mainsite/templates/_partials/base_js.html
<script>
  function mobile_nav_toggle() {
    $("nav > a").slideToggle(300);
  }

  $(window).resize(function () {
    if(window.innerWidth > 475) {
      $("nav > a").show(0);
    }
    else {
      $("nav > a").hide(0);
    }
  });
</script>

mainsite/templates/_partials/footer.html
{% load static %}

    <footer>
      <div id="footer_content">
        <div id="sponsors">
          <img src="{% static "img/ens_psl.png" %}"
               alt="École Normale Supérieure de Paris | Université Paris Sciences et Lettres"
               title="École Normale Supérieure de Paris | Université Paris Sciences et Lettres"
               />
          <img src="{% static "img/cof.svg" %}"
               alt="COF de l'ENS"
               title="COF de l'ENS"
               />
        </div>
        <ul id="footer_links">
          <li><a href="{% url "mainsite:md_page" "who_are_we" %}">
              <i class="fa fa-users" aria-hidden="true"></i>
              Qui sommes-nous ?
            </a></li>
          <li><a href="{% url "mainsite:md_page" "who_are_we" %}#contact_us">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              Nous contacter
            </a></li>
          <li><a href="{% url "mainsite:md_page" "code_of_conduct" %}">
              <i class="fa fa-gavel" aria-hidden="true"></i>
              Charte de bonne conduite
            </a></li>
        </ul>
      </div>
    </footer>

mainsite/templates/_partials/head.html
{% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ready, Make, Play!</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" />
    <link rel="shortcut icon" type="image/png" href="/static/img/favicon.png"/>
    <script src="{% static "js/jquery-3.4.1.min.js" %}"></script>

mainsite/templates/_partials/header.html
{% load static %}

    <header>
      <div class="head_logo">
        <a href="{% url "mainsite:home" %}">
          <img src="{% static "img/logo.svg" %}" alt="Ready, Make, Play!" />
        </a>
      </div>

      <div id="head_main_infos">
        <div id="location">ENS Ulm,</div>
        <div id="date">24-26 avril 2020</div>
      </div>
    </header>

    <nav>
      <div id="mobile_nav_trigger" onclick="mobile_nav_toggle()">
        <i class="fa fa-bars" aria-hidden="true"></i>
        Menu
      </div>
      {% with url_name=request.resolver_match.url_name slug=request.resolver_match.kwargs.slug %}
      <a {% if url_name == "home" %}class="current"{% endif %} href="{% url "mainsite:home" %}" title="Accueil">
        <i class="fa fa-home" aria-hidden="true"></i>
      </a>
      <a {% if url_name == "md_page" and slug == "practical_information" %}class="current"{% endif %} href="{% url "mainsite:md_page" "practical_information" %}">
        Infos pratiques
      </a>
      <a {% if url_name == "md_page" and slug == "faq" %}class="current"{% endif %} href="{% url "mainsite:md_page" "faq" %}">
        FAQ
      </a>

      {% if user.is_authenticated %}
      {% if user.is_staff %}
      <a href="{% url "admin_pages:index" %}">
        Admin
      </a>
      {% endif %}
      {% if user.contestant %}
      <a {% if is_my_registration %}class="current"{% endif %} href="{% url "registration:registration" %}">
        <i class="fa fa-user-circle" aria-hidden="true"></i>
        Mon inscription
      </a>
      {% endif %}
      <a href="{% url "registration:logout" %}" title="Déconnexion">
        <i class="fa fa-sign-out" aria-hidden="true"></i>
      </a>
      {% else %}
      <a
        {% if is_registration %}class="current"{% endif %}
        href="{% url "registration:register_start" %}">
        <i class="fa fa-file-text" aria-hidden="true"></i>
        S'inscrire
      </a>
      <a
        {% if url_name == "login" %}class="current"{% endif %}
        href="{% url "registration:login" %}?next={{ request.path }}">
        <i class="fa fa-user-circle" aria-hidden="true"></i>
        Connexion
      </a>
      {% endif %}
      {% endwith %}
    </nav>

mainsite/templates/_partials/messages.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %}